### ISSUE TITLE
FastAPI issue

### ISSUE THREAD

**Issue by EnragedAntelope** [SOELexicon/ComfyUI-LexTools#11]
Hi,
Thank you for making this!
Please review how this is importing fastapi - may be a capitalization error? Not sure if something changed between versions of fastapi but trying to run lextools consistently throws this error:

```
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-LexTools\__init__.py", line 2, in <module>
    from .nodes import SegformerNode,ImageCaptioningNode,ImageProcessingNode
  File "D:\ComfyUI\custom_nodes\ComfyUI-LexTools\nodes\ImageProcessingNode.py", line 2, in <module>
    from fastapi import FastApi
ImportError: cannot import name 'FastApi' from 'fastapi' (D:\ComfyUI\venv\Lib\site-packages\fastapi\__init__.py)
```

**Comment by secretivebanana** [comment]
Hello, I had the same problem and managed to fix it. Here's how:
1. In the "ComfyUI-LexTools\nodes" folder, open ImageProcessingNode.py in a text editor.  
2. On the second line, change:
"from fastapi import FastApi" 
to 
"from fastapi import FastAPI" 
(It seems that API needs to be fully capitalized.)
3. Save the file.
4. Restart ComfiUI.

**Comment by EnragedAntelope** [comment]
Thank you, I appreciate that. I am hopeful the dev will incorporate this fix into the repo!

**Comment by 6DEADSHOT9** [comment]
Hi, I have opened up a PR #12 with the fix for the same issue.
