### ISSUE TITLE
Fastapi

### ISSUE THREAD

**Issue by offmybach** [SOELexicon/ComfyUI-LexTools#5]
Failed to load

 File "D:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-LexTools\nodes\ImageProcessingNode.py", line 2, in <module>
    import fastapi
ModuleNotFoundError: No module named 'fastapi'

**Comment by Krazon** [comment]
Same, can't get this to work :/
```
/_\ Checking packages
/_\ Installing pillow
/_\ Installing fastapi
Traceback (most recent call last):
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-LexTools\__init__.py", line 2, in <module>
    from .nodes import SegformerNode,ImageCaptioningNode,ImageProcessingNode
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-LexTools\nodes\ImageProcessingNode.py", line 2, in <module>
    import fastapi
ModuleNotFoundError: No module named 'fastapi'

Cannot import D:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-LexTools module for custom nodes: No module named 'fastapi'
```

running `pip install fastapi` shows this
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: fastapi in c:\python\lib\site-packages (0.110.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\python\lib\site-packages (from fastapi) (2.6.4)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in c:\python\lib\site-packages (from fastapi) (0.36.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\python\lib\site-packages (from fastapi) (4.10.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\python\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\python\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.16.3)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\python\lib\site-packages (from starlette<0.37.0,>=0.36.3->fastapi) (4.3.0)
Requirement already satisfied: idna>=2.8 in c:\python\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi) (3.6)
Requirement already satisfied: sniffio>=1.1 in c:\python\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\python\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi) (1.2.0)
```

**Comment by SOELexicon** [comment]
fixed inm latest merge
